# Generate a development environment with 
# a dev env (php backend), a database (mysql) and a database managment tool (adminer)
version: "3"
services:
  # Launch the backend dev env as describe in ./docker/dev.dockerfile
  devenv:
    container_name: api
    build:
      context: ./
      dockerfile: docker/dev-env.dockerfile
    volumes:
      - .:/home/dev/api
    ports:
      - 8000:8000
    # These variables overwrites the ones defined in .env. 
    # Before editing them, make sure the new values corespond to the ones in the "database" service.
    environment: 
      - DB_HOST=database
      - DB_DATABASE=dev_api
      - DB_USERNAME=dev
      - DB_PASSWORD=password
    # Print welcome message then do nothing, just keep the service open for future connections.
    command: sh -c "echo \"Development environment is up. Copy your private ssh keys into .ssh/ (in the project root) to use git.\" && sleep infinity"
    links:
      - database

  # Launch MySQL
  database:
    container_name: api-dev-db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dev_api
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - database